### ISSUE TITLE
Create POST endpoint

### ISSUE THREAD

**Issue by c0nsy** [Hermes-Marketing/hermes#7]
using fast api create the POST endpoint for creating a business

3. Create a New Business
URL: /api/businesses
Method: POST
Description: Add a new business to the list.

Database should handle creating a new id for this, if it doesnt look into how firebase can handle this (should be an int)

look at the database/spreadsheet for all the required fields this needs

Default advertising tier should be standard unless it is specified

**Comment by MinaManso** [comment]
instead of using businesses, we are now using company going forward
